# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Release

on: 
  push:
    tags: 
      - v*

permissions: 
  contents: write  

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - uses: pnpm/action-setup@v2.2.4 
    - name: Restore dependencies
      run: dotnet restore
    - name: Build backend
      run: dotnet build --no-restore
    - name: Install frontend
      run: pnpm install --frozen-lockfile
    - name: Build frontend
      run: pnpm build
    - name: Publish
      run: dotnet publish -c Release -p:Publishdir=../Release
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        files: |
          Release/API.exe
          Release/appsettings.json
